language: ruby
cache: bundler
sudo: false
rvm:
 - 2.1
 - 2.2
 - 2.3
 - 2.4
script:
 - bundle exec jekyll build
 - grep cjtu/blog _site/index.html
 - grep post-title         _site/index.html
 - grep pagination-item    _site/index.html
 - grep cjtu/blog _site/css/blog.css
 - grep 404                _site/404.html
